config/routes.rb
Rails.application.routes.draw do

  root 'palindrome#show'
  post 'create' => 'palindrome#create'
  get  'show_p/:id' => 'palindrome#show_p', as: 'show_p'
  get  'display' => 'palindrome#display'

end

app/models/palindrome.rb
class Palindrome < ActiveRecord::Base

	def palindromize(input_value)
		return input_value if is_palindrome?(input_value)
		array = input_value.to_s.split('').map{|chr| chr.to_i}
		mirrored = mirror(array)
		return mirrored.join.to_i if mirrored.join.to_i > array.join.to_i
		array = (array.join.to_i + 10**(array.length/2)).to_s.split('').map{|chr| chr.to_i}
		mirrored = mirror(array)
		return mirrored.join.to_i
	end

	private

	def is_palindrome?(value)
		value.to_s == value.to_s.reverse
	end

	def mirror(array)
		mirrored = []
		(array.length.to_f/2.0).round.times do |i|
			mirrored << array[i]
		end
		(array.length/2).times do |i|
			mirrored << array[array.length/2-(i+1)]
		end
		return mirrored
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/palindrome_controller.rb
class PalindromeController < ApplicationController

	def show
		@value = Palindrome.new
	end

	def create
		safe_params = params.require(:palindrome).permit(:input_value)
		@value = Palindrome.new(safe_params)
		@value.palindrome = @value.palindromize(@value.input_value)
		@value.save
		#render body: YAML::dump(@value)
		redirect_to show_p_path(id: @value.id)
	end

	def show_p
		@value = Palindrome.find(params[:id])
	end

	def display
		@data = Palindrome.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/palindrome_helper.rb
module PalindromeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Palindromizer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header class="navbar navbar-fixed-top navbar-inverse">
		<h1 text-decoration = 'none'><%= link_to 'THE PALINDROMIZER!!', root_path %><h1>
	</header>

	<%= yield %>

	<p><%= link_to 'See previous entries', display_path %></p>

	<footer>
		<%= debug(params) if Rails.env.development? %>
	</footer>

</body>
</html>

app/views/palindrome/display.html.erb
<h2>Previous Entries</h2>

<table style = "font-size:18px" border = 1px>
	<tr>
		<th>Input value</th>
		<th>Palindrome</th>
	</tr>
	<% @data.each do |data| %>
	<tr>
		<td><%= data.input_value %></td>
		<td><%= data.palindrome %></td>
	<tr>
	<% end %>
<table>

app/views/palindrome/show.html.erb
<div class="col-md-6 col-md-offset-3">
	<%= form_for(@value, :url => create_path) do |f| %>
		<%= f.label :input_value, "Give me an integer" %>
		<%= f.text_field :input_value %>

		<%= f.submit "Submit" %>
	<% end %>
</div>

app/views/palindrome/show_p.html.erb
<%= @value.palindrome %>

<p><%= link_to "Try again", root_path %></p>